[workspace]
channels = ["conda-forge"]
name = "crs"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pymc = ">=5.22.0,<6"
ipykernel = ">=6.29.5,<7"
seaborn = ">=0.13.2,<0.14"
ipywidgets = ">=8.1.7,<9"
